"""rename department

Revision ID: 6000de5cae59
Revises: 4f107e0bba62
Create Date: 2025-06-11 08:14:15.309803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6000de5cae59'
down_revision = '4f107e0bba62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  op.rename_table('departments', 'department')
    # ### end Alembic commands ###
